const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const COOKIE="disputr_session";
const SESSION_SECONDS=60*60*24*30;
const MAX_FILE=10*1024*1024;
const DISCLAIMER="Suggested wording only. Check every fact and personalise it before using it. Disputr does not provide legal advice or guarantee an outcome.";
const ALLOWED_FILES=new Set(["application/pdf","image/jpeg","image/png","image/webp","text/plain"]);

export default {async fetch(request,env){
 const url=new URL(request.url);
 try{
  if(url.pathname==="/api/health") return json({ok:true,service:"Disputr V2",database:Boolean(env.DB),evidence:Boolean(env.EVIDENCE_BUCKET),ai:Boolean(env.OPENAI_API_KEY),stripe:Boolean(env.STRIPE_SECRET_KEY&&env.STRIPE_PRICE_ID)});
  if(request.method==="POST"&&url.pathname==="/api/webhooks/stripe") return stripeWebhook(request,env);
  if(url.pathname.startsWith("/api/")&&isWrite(request.method)&&!sameOrigin(request)) return json({error:"Invalid request origin."},403);
  if(request.method==="POST"&&url.pathname==="/api/auth/register") return register(request,env);
  if(request.method==="POST"&&url.pathname==="/api/auth/login") return login(request,env);
  if(request.method==="POST"&&url.pathname==="/api/auth/logout") return logout(request,env);
  if(request.method==="GET"&&url.pathname==="/api/me") return me(request,env);
  if(request.method==="POST"&&url.pathname==="/api/generate-complaint") return generate(request,env);
  if(request.method==="POST"&&url.pathname==="/api/billing/create-checkout-session") return checkout(request,env);
  if(request.method==="POST"&&url.pathname==="/api/billing/create-portal-session") return portal(request,env);
  if(url.pathname==="/api/complaints"&&request.method==="GET") return listComplaints(request,env);
  if(url.pathname==="/api/complaints"&&request.method==="POST") return createComplaint(request,env);
  if(url.pathname==="/api/reminders"&&request.method==="GET") return listReminders(request,env);
  if(url.pathname==="/api/reminders"&&request.method==="POST") return createReminder(request,env);
  if(url.pathname==="/api/support"&&request.method==="POST") return support(request,env);
  let m=url.pathname.match(/^\/api\/reminders\/([^/]+)$/); if(m&&request.method==="DELETE") return deleteReminder(request,env,m[1]);
  m=url.pathname.match(/^\/api\/complaints\/([^/]+)\/events$/); if(m&&request.method==="POST") return addEvent(request,env,m[1]);
  m=url.pathname.match(/^\/api\/complaints\/([^/]+)\/evidence$/); if(m&&request.method==="GET") return listEvidence(request,env,m[1]);
  if(m&&request.method==="POST") return uploadEvidence(request,env,m[1]);
  m=url.pathname.match(/^\/api\/complaints\/([^/]+)\/evidence\/([^/]+)\/download$/); if(m&&request.method==="GET") return downloadEvidence(request,env,m[1],m[2]);
  m=url.pathname.match(/^\/api\/complaints\/([^/]+)\/evidence\/([^/]+)$/); if(m&&request.method==="DELETE") return deleteEvidence(request,env,m[1],m[2]);
  m=url.pathname.match(/^\/api\/complaints\/([^/]+)$/); if(m&&request.method==="GET") return getComplaint(request,env,m[1]);
  if(m&&request.method==="PATCH") return updateComplaint(request,env,m[1]);
  if(m&&request.method==="DELETE") return deleteComplaint(request,env,m[1]);
  if(url.pathname.startsWith("/api/")) return json({error:"API route not found."},404);
  const response=await env.ASSETS.fetch(request); return secure(response);
 }catch(e){console.error(e);return json({error:"Server error."},500)}
}};

function json(v,s=200,h={}){return new Response(JSON.stringify(v),{status:s,headers:{...JSON_HEADERS,...h}})}
function text(v){return typeof v==="string"?v.trim():""}
function isWrite(m){return !["GET","HEAD","OPTIONS"].includes(m)}
function sameOrigin(r){const o=r.headers.get("origin");if(!o)return true;return o===new URL(r.url).origin}
function secure(r){const h=new Headers(r.headers);h.set("x-content-type-options","nosniff");h.set("referrer-policy","strict-origin-when-cross-origin");h.set("permissions-policy","camera=(), microphone=(), geolocation=()");h.set("content-security-policy","default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'");return new Response(r.body,{status:r.status,statusText:r.statusText,headers:h})}
function cookie(token,max=SESSION_SECONDS){return `${COOKIE}=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${max}`}
function cookies(r){return Object.fromEntries((r.headers.get("cookie")||"").split(";").map(x=>x.trim().split("=")).filter(x=>x.length===2))}
function id(){return crypto.randomUUID()}
function b64(bytes){return btoa(String.fromCharCode(...bytes))}
function unb64(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function sha(s){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function passwordHash(p,salt){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(p),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt:unb64(salt),iterations:180000},key,256);return b64(new Uint8Array(bits))}
async function auth(r,env){const raw=cookies(r)[COOKIE];if(!raw)return null;const th=await sha(raw);return env.DB.prepare(`SELECT u.id,u.email,u.name,u.premium,u.stripe_customer_id FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>unixepoch()`).bind(th).first()}
async function requireUser(r,env){const u=await auth(r,env);return u||null}
async function body(r){try{return await r.json()}catch{return {}}}

async function register(r,env){const b=await body(r),email=text(b.email).toLowerCase(),name=text(b.name).slice(0,100),p=String(b.password||"");if(!/^\S+@\S+\.\S+$/.test(email)||p.length<10)return json({error:"Enter a valid email and a password of at least 10 characters."},400);if(await env.DB.prepare("SELECT id FROM users WHERE email=?").bind(email).first())return json({error:"An account already exists for this email."},409);const salt=b64(crypto.getRandomValues(new Uint8Array(16))),ph=await passwordHash(p,salt),uid=id(),token=b64(crypto.getRandomValues(new Uint8Array(32))),th=await sha(token);await env.DB.batch([env.DB.prepare("INSERT INTO users(id,email,name,password_hash,password_salt) VALUES(?,?,?,?,?)").bind(uid,email,name,ph,salt),env.DB.prepare("INSERT INTO sessions(id,user_id,token_hash,expires_at) VALUES(?,?,?,unixepoch()+?)").bind(id(),uid,th,SESSION_SECONDS)]);return json({ok:true,user:{id:uid,email,name,premium:0}},201,{"set-cookie":cookie(token)})}
async function login(r,env){const b=await body(r),email=text(b.email).toLowerCase(),p=String(b.password||""),u=await env.DB.prepare("SELECT * FROM users WHERE email=?").bind(email).first();if(!u||await passwordHash(p,u.password_salt)!==u.password_hash)return json({error:"Email or password is incorrect."},401);const token=b64(crypto.getRandomValues(new Uint8Array(32))),th=await sha(token);await env.DB.prepare("INSERT INTO sessions(id,user_id,token_hash,expires_at) VALUES(?,?,?,unixepoch()+?)").bind(id(),u.id,th,SESSION_SECONDS).run();return json({ok:true,user:{id:u.id,email:u.email,name:u.name,premium:u.premium}},200,{"set-cookie":cookie(token)})}
async function logout(r,env){const raw=cookies(r)[COOKIE];if(raw)await env.DB.prepare("DELETE FROM sessions WHERE token_hash=?").bind(await sha(raw)).run();return json({ok:true},200,{"set-cookie":cookie("",0)})}
async function me(r,env){const u=await auth(r,env);if(!u)return json({authenticated:false});const sub=await env.DB.prepare("SELECT status,premium,trial_end,current_period_end,cancel_at_period_end FROM subscriptions WHERE user_id=? ORDER BY updated_at DESC LIMIT 1").bind(u.id).first();return json({authenticated:true,user:u,subscription:sub||null})}

async function usage(r,env,u){const day=new Date().toISOString().slice(0,10);let key,limit;if(u){key=`u:${u.id}`;limit=Number(u.premium?env.AI_PREMIUM_DAILY_LIMIT:env.AI_FREE_DAILY_LIMIT)|| (u.premium?40:3)}else{key=`g:${await sha((r.headers.get("cf-connecting-ip")||"unknown")+":"+(env.RATE_LIMIT_SALT||"disputr"))}`;limit=Number(env.AI_GUEST_DAILY_LIMIT)||1}const row=await env.DB.prepare("SELECT uses FROM ai_usage_daily WHERE usage_key=? AND usage_day=?").bind(key,day).first();if((row?.uses||0)>=limit)return {ok:false,limit};await env.DB.prepare("INSERT INTO ai_usage_daily(usage_key,usage_day,uses) VALUES(?,?,1) ON CONFLICT(usage_key,usage_day) DO UPDATE SET uses=uses+1,updated_at=unixepoch()").bind(key,day).run();return {ok:true,limit,used:(row?.uses||0)+1}}
async function generate(r,env){if(!env.OPENAI_API_KEY)return json({error:"AI is not configured."},503);const b=await body(r),required=["category","company","issueType","whatHappened","desiredOutcome"];if(required.some(k=>!text(b[k])))return json({error:"Please complete all required complaint details."},400);const u=await auth(r,env),q=await usage(r,env,u);if(!q.ok)return json({error:"Daily AI limit reached.",limit:q.limit},429);const facts={category:text(b.category).slice(0,100),company:text(b.company).slice(0,150),issue_type:text(b.issueType).slice(0,150),incident_date:text(b.incidentDate).slice(0,100)||"Not provided",reference_number:text(b.referenceNumber).slice(0,150)||"Not provided",what_happened:text(b.whatHappened).slice(0,5000),previous_contact:text(b.priorContact).slice(0,2000)||"Not provided",costs_or_losses:text(b.costsOrLosses).slice(0,1500)||"Not provided",desired_outcome:text(b.desiredOutcome).slice(0,2000)};const schema={type:"object",additionalProperties:false,required:["title","subject","recipient_suggestion","draft","facts_to_check","suggested_attachments","suggested_next_step"],properties:{title:{type:"string"},subject:{type:"string"},recipient_suggestion:{type:"string"},draft:{type:"string"},facts_to_check:{type:"array",items:{type:"string"}},suggested_attachments:{type:"array",items:{type:"string"}},suggested_next_step:{type:"string"}}};const resp=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{authorization:`Bearer ${env.OPENAI_API_KEY}`,"content-type":"application/json"},body:JSON.stringify({model:env.OPENAI_MODEL||"gpt-5.6-luna",store:false,input:[{role:"developer",content:"Write a professional UK-English consumer complaint draft using only supplied facts. Do not invent facts, law, rights, deadlines or outcomes; do not give legal advice. Be factual, polite and firm. Missing facts go in facts_to_check."},{role:"user",content:JSON.stringify(facts)}],text:{format:{type:"json_schema",name:"complaint_template",strict:true,schema}},max_output_tokens:1800})});const p=await resp.json();if(!resp.ok)return json({error:"Draft generation is temporarily unavailable."},502);const out=(p.output||[]).flatMap(x=>x.content||[]).find(x=>x.type==="output_text")?.text;if(!out)return json({error:"AI returned no usable draft."},502);let result;try{result=JSON.parse(out)}catch{return json({error:"AI returned an unexpected response."},502)}return json({...result,disclaimer:DISCLAIMER,usage:{used:q.used,limit:q.limit}})}

async function listComplaints(r,env){const u=await requireUser(r,env);if(!u)return json({error:"Sign in required."},401);const x=await env.DB.prepare("SELECT id,case_ref,category,company,issue_type,title,status,stage,response_due_at,updated_at FROM complaints WHERE user_id=? ORDER BY updated_at DESC").bind(u.id).all();return json({complaints:x.results||[]})}
async function createComplaint(r,env){const u=await requireUser(r,env);if(!u)return json({error:"Sign in required."},401);const b=await body(r),company=text(b.company),category=text(b.category),issue=text(b.issueType),title=text(b.title)||`${company} complaint`;if(!company||!category||!issue)return json({error:"Company, category and issue type are required."},400);const cid=id(),ref=`DSP-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${cid.slice(0,6).toUpperCase()}`;await env.DB.prepare(`INSERT INTO complaints(id,case_ref,user_id,category,company,issue_type,title,status,stage,incident_date,reference_number,what_happened,prior_contact,costs_or_losses,desired_outcome,draft_text) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(cid,ref,u.id,category,company,issue,title,text(b.status)||"draft",text(b.stage)||"prepare",text(b.incidentDate)||null,text(b.referenceNumber)||null,text(b.whatHappened)||null,text(b.priorContact)||null,text(b.costsOrLosses)||null,text(b.desiredOutcome)||null,text(b.draftText)||null).run();await env.DB.prepare("INSERT INTO complaint_events(id,complaint_id,user_id,event_type,title,event_at) VALUES(?,?,?,?,?,unixepoch())").bind(id(),cid,u.id,"created","Case created").run();return json({ok:true,id:cid,case_ref:ref},201)}
async function owned(env,u,cid){return env.DB.prepare("SELECT * FROM complaints WHERE id=? AND user_id=?").bind(cid,u.id).first()}
async function getComplaint(r,env,cid){const u=await requireUser(r,env);if(!u)return json({error:"Sign in required."},401);const c=await owned(env,u,cid);if(!c)return json({error:"Case not found."},404);const ev=await env.DB.prepare("SELECT * FROM complaint_events WHERE complaint_id=? AND user_id=? ORDER BY event_at DESC").bind(cid,u.id).all();const rem=await env.DB.prepare("SELECT * FROM reminders WHERE complaint_id=? AND user_id=? ORDER BY due_at").bind(cid,u.id).all();return json({complaint:c,events:ev.results||[],reminders:rem.results||[]})}
async function updateComplaint(r,env,cid){const u=await requireUser(r,env);if(!u)return json({error:"Sign in required."},401);if(!await owned(env,u,cid))return json({error:"Case not found."},404);const b=await body(r);const fields={title:"title",status:"status",stage:"stage",incidentDate:"incident_date",referenceNumber:"reference_number",whatHappened:"what_happened",priorContact:"prior_contact",costsOrLosses:"costs_or_losses",desiredOutcome:"desired_outcome",draftText:"draft_text",sentAt:"sent_at",responseDueAt:"response_due_at",finalResponseAt:"final_response_at"};const sets=[],vals=[];for(const [k,col] of Object.entries(fields))if(Object.hasOwn(b,k)){sets.push(`${col}=?`);vals.push(typeof b[k]==="string"?text(b[k]):b[k]}if(!sets.length)return json({error:"No changes supplied."},400);sets.push("updated_at=unixepoch()");await env.DB.prepare(`UPDATE complaints SET ${sets.join(",")} WHERE id=? AND user_id=?`).bind(...vals,cid,u.id).run();return json({ok:true})}
async function deleteComplaint(r,env,cid){const u=await requireUser(r,env);if(!u)return json({error:"Sign in required."},401);if(!await owned(env,u,cid))return json({error:"Case not found."},404);const files=await env.DB.prepare("SELECT object_key FROM complaint_evidence WHERE complaint_id=? AND user_id=?").bind(cid,u.id).all();for(const f of files.results||[])await env.EVIDENCE_BUCKET.delete(f.object_key);await env.DB.prepare("DELETE FROM complaints WHERE id=? AND user_id=?").bind(cid,u.id).run();return json({ok:true})}
async function addEvent(r,env,cid){const u=await requireUser(r,env);if(!u)return json({error:"Sign in required."},401);if(!await owned(env,u,cid))return json({error:"Case not found."},404);const b=await body(r),title=text(b.title);if(!title)return json({error:"Event title is required."},400);await env.DB.prepare("INSERT INTO complaint_events(id,complaint_id,user_id,event_type,title,notes,event_at) VALUES(?,?,?,?,?,?,?)").bind(id(),cid,u.id,text(b.eventType)||"note",title,text(b.notes)||null,Number(b.eventAt)||Math.floor(Date.now()/1000)).run();return json({ok:true},201)}

async function listEvidence(r,env,cid){const u=await requireUser(r,env);if(!u)return json({error:"Sign in required."},401);if(!await owned(env,u,cid))return json({error:"Case not found."},404);const x=await env.DB.prepare("SELECT id,filename,content_type,byte_size,notes,created_at FROM complaint_evidence WHERE complaint_id=? AND user_id=? ORDER BY created_at DESC").bind(cid,u.id).all();return json({evidence:x.results||[]})}
async function uploadEvidence(r,env,cid){const u=await requireUser(r,env);if(!u)return json({error:"Sign in required."},401);if(!env.EVIDENCE_BUCKET)return json({error:"Evidence storage is not configured."},503);if(!await owned(env,u,cid))return json({error:"Case not found."},404);const form=await r.formData(),file=form.get("file"),notes=text(form.get("notes"));if(!(file instanceof File))return json({error:"Choose a file."},400);if(file.size>MAX_FILE)return json({error:"File must be 10MB or smaller."},413);if(!ALLOWED_FILES.has(file.type))return json({error:"Use PDF, JPG, PNG, WEBP or text files."},415);const eid=id(),key=`${u.id}/${cid}/${eid}`;await env.EVIDENCE_BUCKET.put(key,file.stream(),{httpMetadata:{contentType:file.type},customMetadata:{filename:file.name}});await env.DB.prepare("INSERT INTO complaint_evidence(id,complaint_id,user_id,filename,content_type,byte_size,object_key,notes) VALUES(?,?,?,?,?,?,?,?)").bind(eid,cid,u.id,file.name.slice(0,250),file.type,file.size,key,notes||null).run();return json({ok:true,id:eid},201)}
async function evidenceRow(env,u,cid,eid){return env.DB.prepare("SELECT * FROM complaint_evidence WHERE id=? AND complaint_id=? AND user_id=?").bind(eid,cid,u.id).first()}
async function downloadEvidence(r,env,cid,eid){const u=await requireUser(r,env);if(!u)return json({error:"Sign in required."},401);const e=await evidenceRow(env,u,cid,eid);if(!e)return json({error:"Evidence not found."},404);const o=await env.EVIDENCE_BUCKET.get(e.object_key);if(!o)return json({error:"Stored file not found."},404);return new Response(o.body,{headers:{"content-type":e.content_type,"content-disposition":`attachment; filename*=UTF-8''${encodeURIComponent(e.filename)}`,"cache-control":"private, no-store"}})}
async function deleteEvidence(r,env,cid,eid){const u=await requireUser(r,env);if(!u)return json({error:"Sign in required."},401);const e=await evidenceRow(env,u,cid,eid);if(!e)return json({error:"Evidence not found."},404);await env.EVIDENCE_BUCKET.delete(e.object_key);await env.DB.prepare("DELETE FROM complaint_evidence WHERE id=? AND user_id=?").bind(eid,u.id).run();return json({ok:true})}

async function listReminders(r,env){const u=await requireUser(r,env);if(!u)return json({error:"Sign in required."},401);const x=await env.DB.prepare("SELECT r.*,c.case_ref,c.company FROM reminders r JOIN complaints c ON c.id=r.complaint_id WHERE r.user_id=? ORDER BY r.completed,r.due_at").bind(u.id).all();return json({reminders:x.results||[]})}
async function createReminder(r,env){const u=await requireUser(r,env);if(!u)return json({error:"Sign in required."},401);const b=await body(r),cid=text(b.complaintId),title=text(b.title),due=Number(b.dueAt);if(!cid||!title||!due)return json({error:"Case, title and due date are required."},400);if(!await owned(env,u,cid))return json({error:"Case not found."},404);const rid=id();await env.DB.prepare("INSERT INTO reminders(id,complaint_id,user_id,title,due_at) VALUES(?,?,?,?,?)").bind(rid,cid,u.id,title,due).run();return json({ok:true,id:rid},201)}
async function deleteReminder(r,env,rid){const u=await requireUser(r,env);if(!u)return json({error:"Sign in required."},401);await env.DB.prepare("DELETE FROM reminders WHERE id=? AND user_id=?").bind(rid,u.id).run();return json({ok:true})}
async function support(r,env){const u=await auth(r,env),b=await body(r),email=text(b.email||u?.email).toLowerCase(),subject=text(b.subject),message=text(b.message);if(!email||!subject||!message)return json({error:"Email, subject and message are required."},400);const tid=id(),ref=`SUP-${tid.slice(0,8).toUpperCase()}`;await env.DB.prepare("INSERT INTO support_tickets(id,ticket_ref,user_id,email,subject,message) VALUES(?,?,?,?,?,?)").bind(tid,ref,u?.id||null,email,subject.slice(0,200),message.slice(0,5000)).run();return json({ok:true,ticket_ref:ref},201)}

async function stripePost(env,path,params){const r=await fetch(`https://api.stripe.com/v1/${path}`,{method:"POST",headers:{authorization:`Bearer ${env.STRIPE_SECRET_KEY}`,"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams(params)});const p=await r.json();if(!r.ok)throw new Error(p?.error?.message||"Stripe request failed");return p}
async function checkout(r,env){const u=await requireUser(r,env);if(!u)return json({error:"Sign in required."},401);if(!env.STRIPE_SECRET_KEY||!env.STRIPE_PRICE_ID)return json({error:"Billing is not configured."},503);let customer=u.stripe_customer_id;if(!customer){const c=await stripePost(env,"customers",{email:u.email,"metadata[user_id]":u.id});customer=c.id;await env.DB.prepare("UPDATE users SET stripe_customer_id=?,updated_at=unixepoch() WHERE id=?").bind(customer,u.id).run()}const origin=new URL(r.url).origin;const s=await stripePost(env,"checkout/sessions",{mode:"subscription",customer,"line_items[0][price]":env.STRIPE_PRICE_ID,"line_items[0][quantity]":"1","subscription_data[trial_period_days]":String(env.STRIPE_TRIAL_DAYS||14),success_url:`${origin}/dashboard.html?billing=success`,cancel_url:`${origin}/pricing.html?billing=cancelled`,"metadata[user_id]":u.id});return json({url:s.url})}
async function portal(r,env){const u=await requireUser(r,env);if(!u)return json({error:"Sign in required."},401);if(!u.stripe_customer_id)return json({error:"No billing account found."},400);const origin=new URL(r.url).origin,s=await stripePost(env,"billing_portal/sessions",{customer:u.stripe_customer_id,return_url:`${origin}/dashboard.html`});return json({url:s.url})}
function parseSig(s){return Object.fromEntries((s||"").split(",").map(x=>x.split("=")).filter(x=>x.length===2))}
async function hmac(secret,msg){const k=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const d=await crypto.subtle.sign("HMAC",k,new TextEncoder().encode(msg));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function stripeWebhook(r,env){if(!env.STRIPE_WEBHOOK_SECRET)return json({error:"Webhook not configured."},503);const raw=await r.text(),sig=parseSig(r.headers.get("stripe-signature")),t=Number(sig.t);if(!t||Math.abs(Date.now()/1000-t)>300||await hmac(env.STRIPE_WEBHOOK_SECRET,`${t}.${raw}`)!==sig.v1)return json({error:"Invalid signature."},400);const e=JSON.parse(raw);if(await env.DB.prepare("SELECT 1 FROM stripe_webhook_events WHERE stripe_event_id=?").bind(e.id).first())return json({received:true,duplicate:true});const o=e.data?.object||{};if(e.type.startsWith("customer.subscription.")){const uid=o.metadata?.user_id||await userFromCustomer(env,o.customer);if(uid){const premium=["active","trialing"].includes(o.status)?1:0;await env.DB.prepare(`INSERT INTO subscriptions(stripe_subscription_id,stripe_customer_id,user_id,status,premium,current_period_end,trial_end,cancel_at_period_end,last_stripe_event_created) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(stripe_subscription_id) DO UPDATE SET stripe_customer_id=excluded.stripe_customer_id,user_id=excluded.user_id,status=excluded.status,premium=excluded.premium,current_period_end=excluded.current_period_end,trial_end=excluded.trial_end,cancel_at_period_end=excluded.cancel_at_period_end,last_stripe_event_created=excluded.last_stripe_event_created,updated_at=unixepoch()`).bind(o.id,o.customer,uid,o.status,premium,o.current_period_end||null,o.trial_end||null,o.cancel_at_period_end?1:0,e.created||0).run();await env.DB.prepare("UPDATE users SET premium=?,stripe_customer_id=COALESCE(stripe_customer_id,?),updated_at=unixepoch() WHERE id=?").bind(premium,o.customer,uid).run()}}if(e.type==="checkout.session.completed"){const uid=o.metadata?.user_id;if(uid&&o.customer)await env.DB.prepare("UPDATE users SET stripe_customer_id=?,updated_at=unixepoch() WHERE id=?").bind(o.customer,uid).run()}await env.DB.prepare("INSERT INTO stripe_webhook_events(stripe_event_id,event_type,event_created_at,received_at) VALUES(?,?,?,unixepoch())").bind(e.id,e.type,e.created||0).run();return json({received:true})}
async function userFromCustomer(env,c){if(!c)return null;return (await env.DB.prepare("SELECT id FROM users WHERE stripe_customer_id=?").bind(c).first())?.id||null}
