const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const COOKIE="disputr_session";
const SESSION_SECONDS=60*60*24*30;
const PASSWORD_ITERATIONS=100000;
const MAX_FILE=10*1024*1024;
const FILE_TYPES=new Set(["application/pdf","image/jpeg","image/png","image/webp","text/plain"]);
const COMPLAINT_STATUSES=new Set(["draft","sent","waiting","final-response","escalated","resolved","closed"]);
const COMPLAINT_STAGES=new Set(["prepare","submitted","response","escalation","complete"]);
const DISCLAIMER="Suggested wording only. Check every fact and personalise it before using it. Disputr does not provide legal advice or guarantee an outcome.";

export default {async fetch(request,env){
  const url=new URL(request.url);
  try{
    if(url.pathname==="/api/health") return json({ok:true,service:"Disputr V3",database:!!env.DB,evidence:!!env.EVIDENCE_BUCKET,ai:!!env.OPENAI_API_KEY,stripe:!!(env.STRIPE_SECRET_KEY&&env.STRIPE_PRICE_ID&&env.STRIPE_WEBHOOK_SECRET)});
    if(request.method==="POST"&&url.pathname==="/api/webhooks/stripe") return stripeWebhook(request,env);
    if(url.pathname.startsWith("/api/")&&isWrite(request.method)&&!sameOrigin(request)) return json({error:"Invalid request origin."},403);

    const route=`${request.method} ${url.pathname}`;
    if(route==="POST /api/auth/register") return register(request,env);
    if(route==="POST /api/auth/login") return login(request,env);
    if(route==="POST /api/auth/logout") return logout(request,env);
    if(route==="GET /api/me") return me(request,env);
    if(route==="POST /api/generate-complaint") return generateComplaint(request,env);
    if(route==="GET /api/complaints") return listComplaints(request,env);
    if(route==="POST /api/complaints") return createComplaint(request,env);
    if(route==="GET /api/reminders") return listReminders(request,env);
    if(route==="POST /api/reminders") return createReminder(request,env);
    if(route==="POST /api/support") return createSupportTicket(request,env);
    if(route==="POST /api/billing/create-checkout-session") return createCheckout(request,env);
    if(route==="POST /api/billing/create-portal-session") return createPortal(request,env);

    let m=url.pathname.match(/^\/api\/reminders\/([^/]+)$/);
    if(m&&request.method==="PATCH") return updateReminder(request,env,m[1]);
    if(m&&request.method==="DELETE") return deleteReminder(request,env,m[1]);
    m=url.pathname.match(/^\/api\/complaints\/([^/]+)\/events$/);
    if(m&&request.method==="POST") return addEvent(request,env,m[1]);
    m=url.pathname.match(/^\/api\/complaints\/([^/]+)\/evidence$/);
    if(m&&request.method==="GET") return listEvidence(request,env,m[1]);
    if(m&&request.method==="POST") return uploadEvidence(request,env,m[1]);
    m=url.pathname.match(/^\/api\/complaints\/([^/]+)\/evidence\/([^/]+)\/download$/);
    if(m&&request.method==="GET") return downloadEvidence(request,env,m[1],m[2]);
    m=url.pathname.match(/^\/api\/complaints\/([^/]+)\/evidence\/([^/]+)$/);
    if(m&&request.method==="DELETE") return deleteEvidence(request,env,m[1],m[2]);
    m=url.pathname.match(/^\/api\/complaints\/([^/]+)$/);
    if(m&&request.method==="GET") return getComplaint(request,env,m[1]);
    if(m&&request.method==="PATCH") return updateComplaint(request,env,m[1]);
    if(m&&request.method==="DELETE") return deleteComplaint(request,env,m[1]);

    if(url.pathname.startsWith("/api/")) return json({error:"API route not found."},404);
    return secure(await env.ASSETS.fetch(request));
  }catch(err){console.error(err);return json({error:"Server error."},500)}
}};

function json(value,status=200,headers={}){return new Response(JSON.stringify(value),{status,headers:{...JSON_HEADERS,...headers}})}
function text(value){return typeof value==="string"?value.trim():""}
function id(){return crypto.randomUUID()}
function isWrite(method){return !["GET","HEAD","OPTIONS"].includes(method)}
function sameOrigin(request){const origin=request.headers.get("origin");return !origin||origin===new URL(request.url).origin}
function secure(response){const h=new Headers(response.headers);h.set("x-content-type-options","nosniff");h.set("referrer-policy","strict-origin-when-cross-origin");h.set("permissions-policy","camera=(), microphone=(), geolocation=()");h.set("content-security-policy","default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'");h.set("strict-transport-security","max-age=31536000; includeSubDomains");return new Response(response.body,{status:response.status,statusText:response.statusText,headers:h})}
async function body(request){try{return await request.json()}catch{return {}}}
function b64(bytes){return btoa(String.fromCharCode(...bytes))}
function unb64(value){return Uint8Array.from(atob(value),c=>c.charCodeAt(0))}
function randomHex(bytes=32){return [...crypto.getRandomValues(new Uint8Array(bytes))].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function sha(value){const d=new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)));return [...d].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function passwordHash(password,salt){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt:unb64(salt),iterations:PASSWORD_ITERATIONS},key,256);return b64(new Uint8Array(bits))}
function parseCookies(request){const result={};for(const item of (request.headers.get("cookie")||"").split(";")){const s=item.trim();if(!s)continue;const i=s.indexOf("=");if(i>0)result[s.slice(0,i)]=s.slice(i+1)}return result}
function sessionCookie(token,maxAge=SESSION_SECONDS){return `${COOKIE}=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`}
async function currentUser(request,env){const token=parseCookies(request)[COOKIE];if(!token)return null;return env.DB.prepare("SELECT u.id,u.email,u.name,u.premium,u.stripe_customer_id FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>unixepoch()").bind(await sha(token)).first()}
async function requireUser(request,env){return currentUser(request,env)}

async function register(request,env){const b=await body(request),email=text(b.email).toLowerCase(),name=text(b.name).slice(0,100),password=String(b.password||"");if(!/^\S+@\S+\.\S+$/.test(email)||password.length<10||password.length>200)return json({error:"Enter a valid email and a password between 10 and 200 characters."},400);if(email.length>254)return json({error:"Email address is too long."},400);if(await env.DB.prepare("SELECT id FROM users WHERE email=?").bind(email).first())return json({error:"An account already exists for this email."},409);const salt=b64(crypto.getRandomValues(new Uint8Array(16))),userId=id(),token=randomHex();try{await env.DB.batch([env.DB.prepare("INSERT INTO users(id,email,name,password_hash,password_salt) VALUES(?,?,?,?,?)").bind(userId,email,name,await passwordHash(password,salt),salt),env.DB.prepare("INSERT INTO sessions(id,user_id,token_hash,expires_at) VALUES(?,?,?,unixepoch()+?)").bind(id(),userId,await sha(token),SESSION_SECONDS)])}catch(err){if(String(err?.message||err).toLowerCase().includes("unique"))return json({error:"An account already exists for this email."},409);throw err}return json({ok:true,user:{id:userId,email,name,premium:0}},201,{"set-cookie":sessionCookie(token)})}
async function login(request,env){const b=await body(request),email=text(b.email).toLowerCase(),password=String(b.password||"");if(!email||!password||password.length>200)return json({error:"Email or password is incorrect."},401);const u=await env.DB.prepare("SELECT * FROM users WHERE email=?").bind(email).first();if(!u||await passwordHash(password,u.password_salt)!==u.password_hash)return json({error:"Email or password is incorrect."},401);const token=randomHex();await env.DB.batch([env.DB.prepare("DELETE FROM sessions WHERE expires_at<=unixepoch()"),env.DB.prepare("INSERT INTO sessions(id,user_id,token_hash,expires_at) VALUES(?,?,?,unixepoch()+?)").bind(id(),u.id,await sha(token),SESSION_SECONDS)]);return json({ok:true,user:{id:u.id,email:u.email,name:u.name,premium:u.premium}},200,{"set-cookie":sessionCookie(token)})}
async function logout(request,env){const token=parseCookies(request)[COOKIE];if(token)await env.DB.prepare("DELETE FROM sessions WHERE token_hash=?").bind(await sha(token)).run();return json({ok:true},200,{"set-cookie":sessionCookie("",0)})}
async function me(request,env){const u=await currentUser(request,env);if(!u)return json({authenticated:false});const subscription=await env.DB.prepare("SELECT status,premium,trial_end,current_period_end,cancel_at_period_end FROM subscriptions WHERE user_id=? ORDER BY updated_at DESC LIMIT 1").bind(u.id).first();return json({authenticated:true,user:u,subscription:subscription||null})}

async function consumeQuota(request,env,u){const day=new Date().toISOString().slice(0,10);const key=u?`u:${u.id}`:`g:${await sha((request.headers.get("cf-connecting-ip")||"unknown")+":"+(env.RATE_LIMIT_SALT||"disputr"))}`;const limit=Number(u?(u.premium?env.AI_PREMIUM_DAILY_LIMIT:env.AI_FREE_DAILY_LIMIT):env.AI_GUEST_DAILY_LIMIT)||(u?(u.premium?40:3):1);const row=await env.DB.prepare("SELECT uses FROM ai_usage_daily WHERE usage_key=? AND usage_day=?").bind(key,day).first();if((row?.uses||0)>=limit)return{ok:false,limit};await env.DB.prepare("INSERT INTO ai_usage_daily(usage_key,usage_day,uses) VALUES(?,?,1) ON CONFLICT(usage_key,usage_day) DO UPDATE SET uses=uses+1,updated_at=unixepoch()").bind(key,day).run();return{ok:true,limit,used:(row?.uses||0)+1}}
async function generateComplaint(request,env){if(!env.OPENAI_API_KEY)return json({error:"AI is not configured."},503);const b=await body(request);if(["category","company","issueType","whatHappened","desiredOutcome"].some(k=>!text(b[k])))return json({error:"Please complete the company, issue, what happened and desired outcome before generating a draft."},400);const q=await consumeQuota(request,env,await currentUser(request,env));if(!q.ok)return json({error:"Daily AI limit reached.",limit:q.limit},429);const facts={category:text(b.category).slice(0,100),company:text(b.company).slice(0,150),issue_type:text(b.issueType).slice(0,150),incident_date:text(b.incidentDate).slice(0,100)||"Not provided",reference_number:text(b.referenceNumber).slice(0,150)||"Not provided",what_happened:text(b.whatHappened).slice(0,5000),previous_contact:text(b.priorContact).slice(0,2000)||"Not provided",costs_or_losses:text(b.costsOrLosses).slice(0,1500)||"Not provided",desired_outcome:text(b.desiredOutcome).slice(0,2000)};const schema={type:"object",additionalProperties:false,required:["title","subject","recipient_suggestion","draft","facts_to_check","suggested_attachments","suggested_next_step"],properties:{title:{type:"string"},subject:{type:"string"},recipient_suggestion:{type:"string"},draft:{type:"string"},facts_to_check:{type:"array",items:{type:"string"}},suggested_attachments:{type:"array",items:{type:"string"}},suggested_next_step:{type:"string"}}};const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{authorization:`Bearer ${env.OPENAI_API_KEY}`,"content-type":"application/json"},body:JSON.stringify({model:env.OPENAI_MODEL||"gpt-5.6-luna",store:false,input:[{role:"developer",content:"Write a professional UK-English consumer complaint draft using only supplied facts. Do not invent facts, law, rights, deadlines or outcomes. Do not give legal advice. Be factual, polite and firm. Put missing facts in facts_to_check."},{role:"user",content:JSON.stringify(facts)}],text:{format:{type:"json_schema",name:"complaint_template",strict:true,schema}},max_output_tokens:1800})});const payload=await response.json().catch(()=>({}));if(!response.ok)return json({error:"Draft generation is temporarily unavailable."},502);const output=(payload.output||[]).flatMap(x=>x.content||[]).find(x=>x.type==="output_text")?.text;if(!output)return json({error:"AI returned no usable draft."},502);try{return json({...JSON.parse(output),disclaimer:DISCLAIMER,usage:{used:q.used,limit:q.limit}})}catch{return json({error:"AI returned an unexpected response."},502)}}

async function ownedComplaint(env,u,complaintId){return env.DB.prepare("SELECT * FROM complaints WHERE id=? AND user_id=?").bind(complaintId,u.id).first()}
async function listComplaints(request,env){const u=await requireUser(request,env);if(!u)return json({error:"Sign in required."},401);const rows=await env.DB.prepare("SELECT id,case_ref,category,company,issue_type,title,status,stage,response_due_at,updated_at FROM complaints WHERE user_id=? ORDER BY updated_at DESC").bind(u.id).all();return json({complaints:rows.results||[]})}
async function createComplaint(request,env){const u=await requireUser(request,env);if(!u)return json({error:"Sign in required."},401);const b=await body(request),company=text(b.company).slice(0,150),category=text(b.category).slice(0,100),issue=text(b.issueType).slice(0,150);if(!company||!category||!issue)return json({error:"Company, category and issue type are required."},400);const complaintId=id(),ref=`DSP-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${complaintId.slice(0,6).toUpperCase()}`;await env.DB.batch([env.DB.prepare("INSERT INTO complaints(id,case_ref,user_id,category,company,issue_type,title,status,stage,incident_date,reference_number,what_happened,prior_contact,costs_or_losses,desired_outcome,draft_text) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(complaintId,ref,u.id,category,company,issue,text(b.title).slice(0,200)||`${company} complaint`,"draft","prepare",text(b.incidentDate).slice(0,30)||null,text(b.referenceNumber).slice(0,150)||null,text(b.whatHappened).slice(0,5000)||null,text(b.priorContact).slice(0,2000)||null,text(b.costsOrLosses).slice(0,1500)||null,text(b.desiredOutcome).slice(0,2000)||null,text(b.draftText).slice(0,20000)||null),env.DB.prepare("INSERT INTO complaint_events(id,complaint_id,user_id,event_type,title,event_at) VALUES(?,?,?,?,?,unixepoch())").bind(id(),complaintId,u.id,"created","Case created")]);return json({ok:true,id:complaintId,case_ref:ref},201)}
async function getComplaint(request,env,complaintId){const u=await requireUser(request,env);if(!u)return json({error:"Sign in required."},401);const complaint=await ownedComplaint(env,u,complaintId);if(!complaint)return json({error:"Case not found."},404);const [events,reminders]=await Promise.all([env.DB.prepare("SELECT * FROM complaint_events WHERE complaint_id=? AND user_id=? ORDER BY event_at DESC").bind(complaintId,u.id).all(),env.DB.prepare("SELECT * FROM reminders WHERE complaint_id=? AND user_id=? ORDER BY completed,due_at").bind(complaintId,u.id).all()]);return json({complaint,events:events.results||[],reminders:reminders.results||[]})}
async function updateComplaint(request,env,complaintId){const u=await requireUser(request,env);if(!u)return json({error:"Sign in required."},401);if(!await ownedComplaint(env,u,complaintId))return json({error:"Case not found."},404);const b=await body(request);if(Object.hasOwn(b,"status")&&!COMPLAINT_STATUSES.has(text(b.status)))return json({error:"Invalid case status."},400);if(Object.hasOwn(b,"stage")&&!COMPLAINT_STAGES.has(text(b.stage)))return json({error:"Invalid case stage."},400);const specs={title:["title",200],status:["status",40],stage:["stage",40],incidentDate:["incident_date",30],referenceNumber:["reference_number",150],whatHappened:["what_happened",5000],priorContact:["prior_contact",2000],costsOrLosses:["costs_or_losses",1500],desiredOutcome:["desired_outcome",2000],draftText:["draft_text",20000]},sets=[],values=[];for(const[k,[column,max]]of Object.entries(specs)){if(Object.hasOwn(b,k)){sets.push(`${column}=?`);values.push(text(b[k]).slice(0,max)||null)}}for(const[k,column]of Object.entries({sentAt:"sent_at",responseDueAt:"response_due_at",finalResponseAt:"final_response_at"})){if(Object.hasOwn(b,k)){const v=b[k]===null?null:Number(b[k]);if(v!==null&&(!Number.isFinite(v)||v<0))return json({error:"Invalid case date."},400);sets.push(`${column}=?`);values.push(v)}}if(!sets.length)return json({error:"No changes supplied."},400);sets.push("updated_at=unixepoch()");await env.DB.prepare(`UPDATE complaints SET ${sets.join(",")} WHERE id=? AND user_id=?`).bind(...values,complaintId,u.id).run();return json({ok:true})}
async function deleteComplaint(request,env,complaintId){const u=await requireUser(request,env);if(!u)return json({error:"Sign in required."},401);if(!await ownedComplaint(env,u,complaintId))return json({error:"Case not found."},404);const files=await env.DB.prepare("SELECT object_key FROM complaint_evidence WHERE complaint_id=? AND user_id=?").bind(complaintId,u.id).all();if(env.EVIDENCE_BUCKET)for(const f of files.results||[])await env.EVIDENCE_BUCKET.delete(f.object_key);await env.DB.prepare("DELETE FROM complaints WHERE id=? AND user_id=?").bind(complaintId,u.id).run();return json({ok:true})}
async function addEvent(request,env,complaintId){const u=await requireUser(request,env);if(!u)return json({error:"Sign in required."},401);if(!await ownedComplaint(env,u,complaintId))return json({error:"Case not found."},404);const b=await body(request),title=text(b.title).slice(0,250),eventAt=Object.hasOwn(b,"eventAt")?Number(b.eventAt):Math.floor(Date.now()/1000);if(!title)return json({error:"Event title is required."},400);if(!Number.isFinite(eventAt)||eventAt<0)return json({error:"Invalid event date."},400);await env.DB.prepare("INSERT INTO complaint_events(id,complaint_id,user_id,event_type,title,notes,event_at) VALUES(?,?,?,?,?,?,?)").bind(id(),complaintId,u.id,text(b.eventType).slice(0,80)||"note",title,text(b.notes).slice(0,3000)||null,eventAt).run();return json({ok:true},201)}

async function listEvidence(request,env,complaintId){const u=await requireUser(request,env);if(!u)return json({error:"Sign in required."},401);if(!await ownedComplaint(env,u,complaintId))return json({error:"Case not found."},404);const rows=await env.DB.prepare("SELECT id,filename,content_type,byte_size,notes,created_at FROM complaint_evidence WHERE complaint_id=? AND user_id=? ORDER BY created_at DESC").bind(complaintId,u.id).all();return json({evidence:rows.results||[]})}
async function uploadEvidence(request,env,complaintId){const u=await requireUser(request,env);if(!u)return json({error:"Sign in required."},401);if(!env.EVIDENCE_BUCKET)return json({error:"Evidence storage is not configured."},503);if(!await ownedComplaint(env,u,complaintId))return json({error:"Case not found."},404);const form=await request.formData(),file=form.get("file");if(!(file instanceof File))return json({error:"Choose a file."},400);if(!file.size)return json({error:"The selected file is empty."},400);if(file.size>MAX_FILE)return json({error:"File must be 10MB or smaller."},413);if(!FILE_TYPES.has(file.type))return json({error:"Use PDF, JPG, PNG, WEBP or text files."},415);const evidenceId=id(),key=`${u.id}/${complaintId}/${evidenceId}`;await env.EVIDENCE_BUCKET.put(key,file.stream(),{httpMetadata:{contentType:file.type},customMetadata:{filename:file.name.slice(0,250)}});try{await env.DB.prepare("INSERT INTO complaint_evidence(id,complaint_id,user_id,filename,content_type,byte_size,object_key,notes) VALUES(?,?,?,?,?,?,?,?)").bind(evidenceId,complaintId,u.id,file.name.slice(0,250),file.type,file.size,key,text(form.get("notes")).slice(0,1000)||null).run()}catch(err){await env.EVIDENCE_BUCKET.delete(key);throw err}return json({ok:true,id:evidenceId},201)}
async function evidenceRow(env,u,complaintId,evidenceId){return env.DB.prepare("SELECT * FROM complaint_evidence WHERE id=? AND complaint_id=? AND user_id=?").bind(evidenceId,complaintId,u.id).first()}
async function downloadEvidence(request,env,complaintId,evidenceId){const u=await requireUser(request,env);if(!u)return json({error:"Sign in required."},401);if(!env.EVIDENCE_BUCKET)return json({error:"Evidence storage is not configured."},503);const row=await evidenceRow(env,u,complaintId,evidenceId);if(!row)return json({error:"Evidence not found."},404);const object=await env.EVIDENCE_BUCKET.get(row.object_key);if(!object)return json({error:"Stored file not found."},404);return new Response(object.body,{headers:{"content-type":row.content_type,"content-disposition":`attachment; filename*=UTF-8''${encodeURIComponent(row.filename)}`,"cache-control":"private, no-store","x-content-type-options":"nosniff"}})}
async function deleteEvidence(request,env,complaintId,evidenceId){const u=await requireUser(request,env);if(!u)return json({error:"Sign in required."},401);if(!env.EVIDENCE_BUCKET)return json({error:"Evidence storage is not configured."},503);const row=await evidenceRow(env,u,complaintId,evidenceId);if(!row)return json({error:"Evidence not found."},404);await env.EVIDENCE_BUCKET.delete(row.object_key);await env.DB.prepare("DELETE FROM complaint_evidence WHERE id=? AND user_id=?").bind(evidenceId,u.id).run();return json({ok:true})}

async function listReminders(request,env){const u=await requireUser(request,env);if(!u)return json({error:"Sign in required."},401);const rows=await env.DB.prepare("SELECT r.*,c.case_ref,c.company FROM reminders r JOIN complaints c ON c.id=r.complaint_id WHERE r.user_id=? ORDER BY r.completed,r.due_at").bind(u.id).all();return json({reminders:rows.results||[]})}
async function createReminder(request,env){const u=await requireUser(request,env);if(!u)return json({error:"Sign in required."},401);const b=await body(request),complaintId=text(b.complaintId),title=text(b.title).slice(0,250),due=Number(b.dueAt);if(!complaintId||!title||!Number.isFinite(due)||due<=0)return json({error:"Case, title and due date are required."},400);if(!await ownedComplaint(env,u,complaintId))return json({error:"Case not found."},404);const reminderId=id();await env.DB.prepare("INSERT INTO reminders(id,complaint_id,user_id,title,due_at) VALUES(?,?,?,?,?)").bind(reminderId,complaintId,u.id,title,due).run();return json({ok:true,id:reminderId},201)}
async function updateReminder(request,env,reminderId){const u=await requireUser(request,env);if(!u)return json({error:"Sign in required."},401);const b=await body(request);if(typeof b.completed!=="boolean")return json({error:"A valid reminder state is required."},400);const result=await env.DB.prepare("UPDATE reminders SET completed=?,updated_at=unixepoch() WHERE id=? AND user_id=?").bind(b.completed?1:0,reminderId,u.id).run();if(!result.meta?.changes)return json({error:"Reminder not found."},404);return json({ok:true})}
async function deleteReminder(request,env,reminderId){const u=await requireUser(request,env);if(!u)return json({error:"Sign in required."},401);const result=await env.DB.prepare("DELETE FROM reminders WHERE id=? AND user_id=?").bind(reminderId,u.id).run();if(!result.meta?.changes)return json({error:"Reminder not found."},404);return json({ok:true})}
async function createSupportTicket(request,env){const u=await currentUser(request,env),b=await body(request),email=text(b.email||u?.email).toLowerCase(),subject=text(b.subject).slice(0,200),message=text(b.message).slice(0,5000);if(!/^\S+@\S+\.\S+$/.test(email)||email.length>254||!subject||!message)return json({error:"A valid email, subject and message are required."},400);const ticketId=id(),ref=`SUP-${ticketId.slice(0,8).toUpperCase()}`;await env.DB.prepare("INSERT INTO support_tickets(id,ticket_ref,user_id,email,subject,message) VALUES(?,?,?,?,?,?)").bind(ticketId,ref,u?.id||null,email,subject,message).run();return json({ok:true,ticket_ref:ref},201)}

async function stripe(env,path,params){const response=await fetch(`https://api.stripe.com/v1/${path}`,{method:"POST",headers:{authorization:`Bearer ${env.STRIPE_SECRET_KEY}`,"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams(params)});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.error?.message||"Stripe request failed");return payload}
async function createCheckout(request,env){const u=await requireUser(request,env);if(!u)return json({error:"Sign in required."},401);if(!env.STRIPE_SECRET_KEY||!env.STRIPE_PRICE_ID)return json({error:"Billing is not configured."},503);const active=await env.DB.prepare("SELECT status FROM subscriptions WHERE user_id=? AND status IN ('active','trialing') LIMIT 1").bind(u.id).first();if(active)return json({error:"Premium is already active. Use Manage Premium instead."},409);let customer=u.stripe_customer_id;if(!customer){const c=await stripe(env,"customers",{email:u.email,"metadata[user_id]":u.id});customer=c.id;await env.DB.prepare("UPDATE users SET stripe_customer_id=?,updated_at=unixepoch() WHERE id=?").bind(customer,u.id).run()}const origin=new URL(request.url).origin;const session=await stripe(env,"checkout/sessions",{mode:"subscription",customer,"line_items[0][price]":env.STRIPE_PRICE_ID,"line_items[0][quantity]":"1","subscription_data[trial_period_days]":String(env.STRIPE_TRIAL_DAYS||14),"subscription_data[metadata][user_id]":u.id,success_url:`${origin}/dashboard.html?billing=success`,cancel_url:`${origin}/pricing.html?billing=cancelled`,"metadata[user_id]":u.id});return json({url:session.url})}
async function createPortal(request,env){const u=await requireUser(request,env);if(!u)return json({error:"Sign in required."},401);if(!env.STRIPE_SECRET_KEY)return json({error:"Billing is not configured."},503);if(!u.stripe_customer_id)return json({error:"No billing account found."},400);const session=await stripe(env,"billing_portal/sessions",{customer:u.stripe_customer_id,return_url:`${new URL(request.url).origin}/dashboard.html`});return json({url:session.url})}
function stripeSignatures(header){const result={t:null,v1:[]};for(const part of (header||"").split(",")){const i=part.indexOf("=");if(i<1)continue;const k=part.slice(0,i),v=part.slice(i+1);if(k==="t")result.t=Number(v);if(k==="v1")result.v1.push(v)}return result}
async function hmac(key,message){const k=await crypto.subtle.importKey("raw",new TextEncoder().encode(key),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const d=new Uint8Array(await crypto.subtle.sign("HMAC",k,new TextEncoder().encode(message)));return [...d].map(x=>x.toString(16).padStart(2,"0")).join("")}
function safeEqual(a,b){if(typeof a!=="string"||typeof b!=="string"||a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0}
async function stripeWebhook(request,env){if(!env.STRIPE_WEBHOOK_SECRET)return json({error:"Webhook not configured."},503);const raw=await request.text(),sig=stripeSignatures(request.headers.get("stripe-signature"));if(!sig.t||Math.abs(Date.now()/1000-sig.t)>300)return json({error:"Invalid signature."},400);const expected=await hmac(env.STRIPE_WEBHOOK_SECRET,`${sig.t}.${raw}`);if(!sig.v1.some(v=>safeEqual(v,expected)))return json({error:"Invalid signature."},400);let event;try{event=JSON.parse(raw)}catch{return json({error:"Invalid payload."},400)}if(!event?.id||!event?.type)return json({error:"Invalid payload."},400);if(await env.DB.prepare("SELECT 1 FROM stripe_webhook_events WHERE stripe_event_id=?").bind(event.id).first())return json({received:true,duplicate:true});const o=event.data?.object||{};if(event.type==="checkout.session.completed"&&o.metadata?.user_id&&o.customer)await env.DB.prepare("UPDATE users SET stripe_customer_id=?,updated_at=unixepoch() WHERE id=?").bind(o.customer,o.metadata.user_id).run();if(event.type.startsWith("customer.subscription.")){const row=await env.DB.prepare("SELECT id FROM users WHERE stripe_customer_id=?").bind(o.customer).first(),userId=o.metadata?.user_id||row?.id;if(userId&&o.id&&o.customer&&o.status){const previous=await env.DB.prepare("SELECT last_stripe_event_created FROM subscriptions WHERE stripe_subscription_id=? OR stripe_customer_id=? LIMIT 1").bind(o.id,o.customer).first(),created=Number(event.created)||0;if(!previous||created>=Number(previous.last_stripe_event_created||0)){const premium=["active","trialing"].includes(o.status)?1:0;await env.DB.prepare("INSERT INTO subscriptions(stripe_subscription_id,stripe_customer_id,user_id,status,premium,current_period_end,trial_end,cancel_at_period_end,last_stripe_event_created) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT DO UPDATE SET stripe_subscription_id=excluded.stripe_subscription_id,stripe_customer_id=excluded.stripe_customer_id,user_id=excluded.user_id,status=excluded.status,premium=excluded.premium,current_period_end=excluded.current_period_end,trial_end=excluded.trial_end,cancel_at_period_end=excluded.cancel_at_period_end,last_stripe_event_created=excluded.last_stripe_event_created,updated_at=unixepoch()").bind(o.id,o.customer,userId,o.status,premium,o.current_period_end||null,o.trial_end||null,o.cancel_at_period_end?1:0,created).run();await env.DB.prepare("UPDATE users SET premium=?,updated_at=unixepoch() WHERE id=?").bind(premium,userId).run()}}}await env.DB.prepare("INSERT INTO stripe_webhook_events(stripe_event_id,event_type,event_created_at,received_at) VALUES(?,?,?,unixepoch())").bind(event.id,event.type,event.created||0).run();return json({received:true})}